### ISSUE TITLE
Will this program handle two instances?

### ISSUE THREAD

**Issue by Russ76** [vash3d/pigpio_encoder#22]
I'd like to use this for a robot with two motors and two wheels. Can the library run two instances of "rotary encoder"?

**Comment by volkerjaenisch** [comment]
To be honest: I do not know.

It depends on the pigpio lib I build this rotary lib on. If the pigpio lib can handle parallel accesses you will be fine.

So please try it out. If you stumble onto problems let me know and I try to help.

Cheers,
Volker

**Comment by Russ76** [comment]
Thanks for the answer. I'll try it. But now, I can't get it to count, even doing one wheel. I get this error (tried it twice):

jeff@raspberrypi:~/scripts$ python3 real_simple.py
Counter value:  -1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/pigpio.py", line 1213, in run
    cb.func(cb.gpio, newLevel, tick)
  File "/home/jeff/scripts/pigpio_encoder/rotary.py", line 121, in dt_gpio_rise
    self.down_callback(self._counter)
TypeError: down_callback() takes 0 positional arguments but 1 was given

^CTraceback (most recent call last):
  File "/home/jeff/scripts/real_simple.py", line 25, in <module>
    my_rotary.watch()
  File "/home/jeff/scripts/pigpio_encoder/rotary.py", line 195, in watch
    time.sleep(10)
KeyboardInterrupt



jeff@raspberrypi:~/scripts$ python3 real_simple.py
Counter value:  1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/pigpio.py", line 1213, in run
    cb.func(cb.gpio, newLevel, tick)
  File "/home/jeff/scripts/pigpio_encoder/rotary.py", line 85, in clk_gpio_rise
    self.up_callback(self._counter)
TypeError: up_callback() takes 0 positional arguments but 1 was given

^CTraceback (most recent call last):
  File "/home/jeff/scripts/real_simple.py", line 25, in <module>
    my_rotary.watch()
  File "/home/jeff/scripts/pigpio_encoder/rotary.py", line 143, in watch
    time.sleep(10)
KeyboardInterrupt

I don't know what it is doing?

**Comment by phr0gger** [comment]
According to the author of pigpio, Joan, you should be able to have multiple objects using PPO at the same time:multiple pigpio pi objectsforums.raspberrypi.comMartinP. S. Volker, bist zu der den ich von der BAM kenne?On Nov 7, 2023, at 23:08, Russ Hall ***@***.***> wrote:﻿
Thanks for the answer. I'll try it. But now, I can't get it to count, even doing one wheel. I get this error (tried it twice):
***@***.***:~/scripts$ python3 real_simple.py
Counter value:  -1
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.10/dist-packages/pigpio.py", line 1213, in run
cb.func(cb.gpio, newLevel, tick)
File "/home/jeff/scripts/pigpio_encoder/rotary.py", line 121, in dt_gpio_rise
self.down_callback(self._counter)
TypeError: down_callback() takes 0 positional arguments but 1 was given
^CTraceback (most recent call last):
File "/home/jeff/scripts/real_simple.py", line 25, in 
my_rotary.watch()
File "/home/jeff/scripts/pigpio_encoder/rotary.py", line 195, in watch
time.sleep(10)
KeyboardInterrupt
***@***.***:~/scripts$ python3 real_simple.py
Counter value:  1
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.10/dist-packages/pigpio.py", line 1213, in run
cb.func(cb.gpio, newLevel, tick)
File "/home/jeff/scripts/pigpio_encoder/rotary.py", line 85, in clk_gpio_rise
self.up_callback(self._counter)
TypeError: up_callback() takes 0 positional arguments but 1 was given
^CTraceback (most recent call last):
File "/home/jeff/scripts/real_simple.py", line 25, in 
my_rotary.watch()
File "/home/jeff/scripts/pigpio_encoder/rotary.py", line 143, in watch
time.sleep(10)
KeyboardInterrupt
I don't know what it is doing?

**Comment by volkerjaenisch** [comment]
@Russ76  
> Thanks for the answer. I'll try it. But now, I can't get it to count, even doing one wheel. I get this error (tried it twice):
> I don't know what it is doing?

Can you please send the Code of your program.

Cheers,
Volker

**Comment by Russ76** [comment]
from pigpio_encoder.rotary import Rotary


def rotary_callback(counter):
  print("Counter value: ", counter)


def sw_short():
  print("Switch pressed")


def up_callback():
  print("Up rotation")


def down_callback():
  print("Down rotation")


my_rotary = Rotary(clk_gpio=17, dt_gpio=18, sw_gpio=19)
my_rotary.setup_rotary(
  rotary_callback=rotary_callback,
  up_callback=up_callback,
  down_callback=down_callback,
)
my_rotary.setup_switch(sw_short_callback=sw_short)

my_rotary.watch()

**Comment by volkerjaenisch** [comment]
@Russ76 
Give these functions 

> def up_callback(): print("Up rotation")
> def down_callback(): print("Down rotation")

a counter variable like you did here

>def rotary_callback(counter):
>print("Counter value: ", counter)

Cheers,
Volker

**Comment by Russ76** [comment]
OK, I'll try that tonight. My program is right from the example script, no?
Thanks

**Comment by Russ76** [comment]
Yes, that took care of it. I had to also change rotary.py line 161 and 162 to zero, instead of self.min, because my min is way, way below zero! It seems to count very fast, with debounce of 10. I will try the two motors tomorrow. Thanks

**Comment by Russ76** [comment]
It will track the encoder ticks from two motors just fine! And I am even using the pigpio library to also send motor control commands from the Raspberry Pi at the same time. Next, I must combine the two encoder outputs into a ROS2 pose message, with quaternion and acceleration information. This is a Raspberry Pi 4 with 2 Gig RAM, running Ubuntu server and Ros Humble.

**Comment by Russ76** [comment]
Thanks for the help. I'll close this now.
