### ISSUE TITLE
Setting min_value in setup_rotary causes not callable exception

### ISSUE THREAD

**Issue by semmelsamu** [vash3d/pigpio_encoder#5]
When i call the setup_rotary function with a min argument, the program tries to set the counter. But its setter calls the rotary_callback function, which at this time is not defined yet.

My code:
`
my_rotary.setup_rotary(min=-1, max=1, scale=1, rotary_callback=rotary_callback)
`

Error:
```Traceback (most recent call last):
  File "main.py", line 13, in <module>
    my_rotary.setup_rotary(min=10, max=300, scale=5, debounce=200, rotary_callback=rotary_callback)
  File "/home/pi/Desktop/pigpio_encoder/src/pigpio_encoder.py", line 119, in setup_rotary
    self.counter = self.min
  File "/home/pi/Desktop/pigpio_encoder/src/pigpio_encoder.py", line 71, in counter
    self.rotary_callback(self._counter)
TypeError: 'NoneType' object is not callable
```

**Comment by volkerjaenisch** [comment]
We are working on this issue. Stay tuned!
